export const GET_ITEM = 'ONCLICK/GET_ITEM'

export const GET_POSITION = 'GET_POSITION_ON_READ_PAGE'

export const CHANGE_ARTICLES_PAGE = 'CHANGE_ARTICLES_PAGE'

export const CHANGE_INPUT = 'CHANGE_INPUT_SEARCH/ON_ARTICLE_PAGE'

export const CHANGE_FILTERED_DATA = 'CHANGE_FILTERED_DATA'

export const CHANGE_HOW_MANY_PAGES = 'CHANGE_HOW_MANY_PAGES'