export const GET_ITEM = 'ONCLICK/GET_ITEM/ARTICLE_PAGE'

export const GET_POSITION = 'GET_POSITION_ON_READ_PAGE/ARTICLE_PAGE'

export const CHANGE_ARTICLES_PAGE = 'CHANGE_HOW_PAGE/ARTICLE_PAGE' /* how page is active */

export const CHANGE_INPUT_ARTICLE = 'CHANGE_INPUT_SEARCH/ARTICLE_PAGE'

export const CHANGE_FILTERED_DATA = 'CHANGE_FILTERED_DATA/ARTICLE_PAGE'

export const CHANGE_HOW_MANY_PAGES = 'CHANGE_HOW_MANY_PAGES/ARTICLE_PAGE'

export const CONTENT_READY_ARTICLES = 'CONTENT_READY_NEWS/ARTICLES_PAGE'