export const GET_ITEM_NEWS = 'ONCLICK/GET_ITEM/NEWS_PAGE'

export const GET_POSITION_NEWS = 'GET_POSITION_ON_READ_PAGE/NEWS_PAGE'

export const CHANGE_NEWS_PAGE_NEWS = 'CHANGE_HOW_PAGE/NEWS_PAGE' /* how page is active */

export const CHANGE_INPUT_NEWS = 'CHANGE_INPUT_SEARCH/NEWS_PAGE'

export const CHANGE_FILTERED_DATA_NEWS = 'CHANGE_FILTERED_DATA/NEWS_PAGE'

export const CHANGE_HOW_MANY_PAGES_NEWS = 'CHANGE_HOW_MANY_PAGES/NEWS_PAGE'

export const CONTENT_READY_NEWS = 'CONTENT_READY_NEWS/NEWS_PAGE'